imports:
    - { resource: parameters.yml }
    - { resource: ns_admin.bundles.yml }
    - { resource: @NSCoreBundle/Resources/config/core-config.yml }

# Framework
framework:
    templating:
        assets_version: 1

# Avalanche Imagine
avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web
    cache_prefix: upload/cache
    filters:
        ns_admin_image:
            type:    thumbnail
            options: { size: [200, 200], mode: inset }
        ns_admin_preview:
            type:    thumbnail
            options: { size: [128, 128], mode: outbound }

        item_slider:
            type: thumbnail
            options: { size: [245, 376], mode: outbound }

        main_news_item:
            type: thumbnail
            options: { size: [180, 120], mode: outbound }

        catalog_item_thumbnail:
            type:    chain
            options:
                filters:
                    thumbnail:
                        # retina x2
                        size: [400, 370]
                        mode: inset

        catalog_item_medium:
            type: thumbnail
            # retina x2
            options: { size: [916, 916], mode: outbound }

        catalog_item_small:
            type: thumbnail
            # retina x2
            options: { size: [196, 196], mode: outbound }

        cart_item_thumbnail:
            type: thumbnail
            options:
                # retina x2
                size: [196, 196]
                mode: inset
