templates:
    -
        path:    "NSCmsBundle:Pages:page.html.twig"
        title:   "Default page template"
        default: true
        areas:
            -
                name: header
                title: "Верхняя область"
                fixed: true
            -
                name: menu
                title: "Область меню"
                fixed: true
            -
                name: content
                title: "Контентная область"
            -
                name: footer1
                title: "Нижняя область 1"
                fixed: true
            -
                name: footer2
                title: "Нижняя область 2"
                fixed: true
            -
                name: footer3
                title: "Нижняя область 3"
                fixed: true
            -
                name: footer4
                title: "Нижняя область 4"
                fixed: true
